name: web tunel
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install soft
        run: |
          (echo 'deb http://pkg.cloudflare.com/ focal main' | sudo tee /etc/apt/sources.list.d/cloudflare-main.list )
          (curl -C - https://pkg.cloudflare.com/pubkey.gpg | sudo apt-key add -)
          sudo apt-get update
          sudo apt-get install -y cloudflared
      - name: sonar docker web
        run: |
         docker network create elastic
         docker pull docker.elastic.co/elasticsearch/elasticsearch:7.15.2
         docker run --name es01-test --net elastic -p 127.0.0.1:8080:9200 -p 127.0.0.1:9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.15.2 & 
      - name: run cloudflared tunel
        run: cloudflared tunnel
